[package]
name = "polynomial-ring"
version = "0.3.3"
authors = ["Toru3 <ryuutet@gmail.com>"]
edition = "2018"
description = "polynomial on field"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/polynomial-ring/"
repository = "https://gitlab.com/Toru3/polynomial-ring"
readme = "README.md"
keywords = ["algebra", "polynomial"]
categories = ["data-structures", "algorithms", "mathematics"]

[dependencies]
num-traits = "0.2.11"
ring-algorithm = "0.3.0"
[dev-dependencies]
num = "0.4.0"
auto_ops = "0.3.0"
[features]
default = []
__internal_inject_debug = [] # DO NOT USE
[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "katex.html",
]
